const express = require("express");
const router = express.Router();
const OwnerRoutes = require("./owner.routes");
const SaloonRotes = require("./saloon.routes");
const BarberRoutes = require("./barber.routes");
const UserRouter = require("./user.routes");
const BarberRatingRoutes = require("./barber.rating.routes");
router.use("/owner", OwnerRoutes);
router.use("/saloon", SaloonRotes);
router.use("/barber", BarberRoutes);
router.use("/barberRating", BarberRatingRoutes);
router.use("/user", UserRouter);
module.exports = router;
